#!/bin/bash

REDIS_SERVER_CONTAINER_NAME="${REDIS_SERVER_CONTAINER_NAME:-redis-server}"
REDIS_SERVER_IMAGE_NAME="${REDIS_SERVER_IMAGE_NAME:-redis/redis-stack-server}"
REDIS_SERVER_PORT="${REDIS_SERVER_PORT:-6379}"