import {
    MAIL_SENDER_NAME,
    MAIL_SENDER_EMAIL,
    MAIL_DOMAIN,
    MAIL_API_KEY,
    POSTMARK_API_KEY,
    MAIL_SERVER_CHOICE,
    TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN,
    TWILIO_MESSAGING_SERVICE_SID,
    TERMII_API_KEY,
    TERMII_BASE_URL,
    SMS_SERVER_CHOICE,
    MESSAGEBIRD_API_KEY,
    FIREBASE_ALL_USERS_TOPIC,
    DEACTIVATE_EMAILS
} from './mainConfig';

export const systemSender: { name: string, email: string } = {
    name: MAIL_SENDER_NAME,
    email: MAIL_SENDER_EMAIL
};

export {
    MAIL_SENDER_NAME,
    MAIL_SENDER_EMAIL,
    MAIL_DOMAIN,
    MAIL_API_KEY,
    POSTMARK_API_KEY,
    MAIL_SERVER_CHOICE,
    SMS_SERVER_CHOICE,
    TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN,
    TWILIO_MESSAGING_SERVICE_SID,
    TERMII_API_KEY,
    TERMII_BASE_URL,
    MESSAGEBIRD_API_KEY,
    FIREBASE_ALL_USERS_TOPIC,
    DEACTIVATE_EMAILS
};